from time import sleep
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
import socket

message = 'Message generated by Bot please ignore'
target = "Famous Five"

driver = webdriver.Chrome()
driver.get('https://web.whatsapp.com')

input("[Enter] after scanning")

def sendMessage(target, message):
    user = driver.find_element_by_xpath("//span[@title='{}']".format(target))
    user.click()

    txt_box=driver.find_element(By.XPATH , '//*[@id="main"]/footer/div[1]/div[2]/div/div[2]')
    txt_box.send_keys(message)
    txt_box.send_keys("\n")


while(1):
    string = driver.switch_to.alert()
    print(string)
